// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttycntukyrmhniyafixk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0eWNudHVreXJtaG5peWFmaXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzMTk3MzMsImV4cCI6MjA5MTg5NTczM30.GZqcWiISKYnmjGgr-_qzMjx_gVERvb-1pFh9t93WBn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});